#include <signal.h>

#define MSVCRT_SIG_ERR (__sighandler_t)-1

static __sighandler_t sighandlers[23];

WINECRT __sighandler_t signal(int sig, __sighandler_t func)
{
    __sighandler_t ret = MSVCRT_SIG_ERR;

    if (func == MSVCRT_SIG_ERR) return MSVCRT_SIG_ERR;

    switch (sig)
    {
    /* Cases handled internally.  Note SIGTERM is never generated by Windows,
     * so we effectively mask it.
     */
    case SIGABRT:
    case SIGFPE:
    case SIGILL:
    case SIGSEGV:
    case SIGINT:
    case SIGTERM:
    case SIGBREAK:
	case SIGALRM:
	case SIGIO:
	case SIGUSR1:
	case SIGUSR2:
	case SIGCHLD:
        ret = sighandlers[sig];
        sighandlers[sig] = func;
        break;
    default:
        ret = MSVCRT_SIG_ERR;
    }
    return ret;
}