#ifndef __STRINGS_OP_H__
#define __STRINGS_OP_H__
#include "cpu.h"
void movsb32_r(struct CPU* cpu, U32 base);
void movsb16_r(struct CPU* cpu, U32 base);
void movsb32(struct CPU* cpu, U32 base);
void movsb16(struct CPU* cpu, U32 base);
void movsw32_r(struct CPU* cpu, U32 base);
void movsw16_r(struct CPU* cpu, U32 base);
void movsw32(struct CPU* cpu, U32 base);
void movsw16(struct CPU* cpu, U32 base);
void movsd32_r(struct CPU* cpu, U32 base);
void movsd16_r(struct CPU* cpu, U32 base);
void movsd32(struct CPU* cpu, U32 base);
void movsd16(struct CPU* cpu, U32 base);
void cmpsb32_r(struct CPU* cpu, U32 rep_zero, U32 base);
void cmpsb16_r(struct CPU* cpu, U32 rep_zero, U32 base);
void cmpsb32(struct CPU* cpu, U32 rep_zero, U32 base);
void cmpsb16(struct CPU* cpu, U32 rep_zero, U32 base);
void cmpsw32_r(struct CPU* cpu, U32 rep_zero, U32 base);
void cmpsw16_r(struct CPU* cpu, U32 rep_zero, U32 base);
void cmpsw32(struct CPU* cpu, U32 rep_zero, U32 base);
void cmpsw16(struct CPU* cpu, U32 rep_zero, U32 base);
void cmpsd32_r(struct CPU* cpu, U32 rep_zero, U32 base);
void cmpsd16_r(struct CPU* cpu, U32 rep_zero, U32 base);
void cmpsd32(struct CPU* cpu, U32 rep_zero, U32 base);
void cmpsd16(struct CPU* cpu, U32 rep_zero, U32 base);
void stosb32_r(struct CPU* cpu);
void stosb16_r(struct CPU* cpu);
void stosb32(struct CPU* cpu);
void stosb16(struct CPU* cpu);
void stosw32_r(struct CPU* cpu);
void stosw16_r(struct CPU* cpu);
void stosw32(struct CPU* cpu);
void stosw16(struct CPU* cpu);
void stosd32_r(struct CPU* cpu);
void stosd16_r(struct CPU* cpu);
void stosd32(struct CPU* cpu);
void stosd16(struct CPU* cpu);
void lodsb32_r(struct CPU* cpu, U32 base);
void lodsb16_r(struct CPU* cpu, U32 base);
void lodsb32(struct CPU* cpu, U32 base);
void lodsb16(struct CPU* cpu, U32 base);
void lodsw32_r(struct CPU* cpu, U32 base);
void lodsw16_r(struct CPU* cpu, U32 base);
void lodsw32(struct CPU* cpu, U32 base);
void lodsw16(struct CPU* cpu, U32 base);
void lodsd32_r(struct CPU* cpu, U32 base);
void lodsd16_r(struct CPU* cpu, U32 base);
void lodsd32(struct CPU* cpu, U32 base);
void lodsd16(struct CPU* cpu, U32 base);
void scasb32_r(struct CPU* cpu, U32 rep_zero);
void scasb16_r(struct CPU* cpu, U32 rep_zero);
void scasb32(struct CPU* cpu, U32 rep_zero);
void scasb16(struct CPU* cpu, U32 rep_zero);
void scasw32_r(struct CPU* cpu, U32 rep_zero);
void scasw16_r(struct CPU* cpu, U32 rep_zero);
void scasw32(struct CPU* cpu, U32 rep_zero);
void scasw16(struct CPU* cpu, U32 rep_zero);
void scasd32_r(struct CPU* cpu, U32 rep_zero);
void scasd16_r(struct CPU* cpu, U32 rep_zero);
void scasd32(struct CPU* cpu, U32 rep_zero);
void scasd16(struct CPU* cpu, U32 rep_zero);
#endif
